# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main  # Change this to your desired branch

# jobs:
#   build:
#     name: Build Docker Image
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERE }}
#           password: ${{ secrets.DOCKERHUB_PASS }}
      
#       - name: Build and Push Docker Image
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ../DevOps/my  
#           push: true
#           tags: sepid5689/my-app:2.0  



# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main  # Change this to your desired branch

# jobs:
#   build_and_push:
#     name: Build Docker Image and Push to Docker Hub
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
      
#       - name: Log into Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_PASS }}
      
#       - name: Build Docker Image
#         run: docker build -t sepid5689/my-app:2.0 .
      
#       - name: Push Docker Image
#         run: docker push sepid5689/my-app:2.0



name: Docker Build and Push

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build_and_push:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: List Repository Content
        run: ls -R  # Print repository content for debugging
      
      - name: Build Docker Image
        run: docker build -t sepid5689/my-app:2.0 .
      
      - name: Push Docker Image
        run: docker push sepid5689/my-app:2.0

